### ISSUE TITLE
데이터를 저장하는 기능

### ISSUE THREAD

**Issue by chaosssanta** [chaosssanta/TputTracingApp#6]
1. 다운로드가 완료된 Idle time에 데이터를 정해진 포맷으로 파일에 Writing한다.
2. 파일이 저장되는 위치는 App의 저장공간에 한다.

**Comment by wonsiklee** [comment]
export format 맞추는 작업만 남은 상태 by 희연J

**Comment by chaosssanta** [comment]
external storage에 저장하도록 함.
